/*
Copyright (c) 2020, Brian Schnepp

Permission is hereby granted, free of charge, to any person or organization 
obtaining  a copy of the software and accompanying documentation covered by 
this license (the "Software") to use, reproduce, display, distribute, execute, 
and transmit the Software, and to prepare derivative works of the Software, 
and to permit third-parties to whom the Software is furnished to do so, all 
subject to the following:

The copyright notices in the Software and this entire statement, including 
the above license grant, this restriction and the following disclaimer, must 
be included in all copies of the Software, in whole or in part, and all 
derivative works of the Software, unless such copies or derivative works are 
solely in the form of machine-executable object code generated by a source 
language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY 
DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
IN THE SOFTWARE.
 */

#include "HTTPCodes.hpp" 

#include <list>
#include <cstdint>
#include <unordered_map>
 
#ifndef _FREEDOMHTTP_SERVER_HPP_
#define _FREEDOMHTTP_SERVER_HPP_

namespace FreedomHTTP
{

typedef struct HTTPRequest
{
	float HTTPVersion;
	HTTPMethod Method;
	std::string Location;
	std::unordered_map<std::string, std::string> Headers;

	uint64_t ContentLength;
	uint8_t *Content;
}HTTPRequest;

HTTPRequest ParseRequest(std::string Content);

typedef struct HTTPResponse
{
	HTTPResponseCode ResponseCode;
	std::unordered_map<std::string, std::string> Headers;
	/* Do it like this to support things that aren't strings */
	uint64_t ContentLength;
	uint8_t *Content;
}HTTPResponse;

typedef HTTPResponse (*EndpointHandler)(void *Data, HTTPRequest Request);

class Server
{
public:
	Server();
	Server(uint16_t Port);
	virtual ~Server(){};
	
	void Run();
	bool Mount(std::string Location, EndpointHandler Handler);
	bool Umount(std::string Location);
	
protected:
	std::unordered_map<std::string, EndpointHandler> Mounts;
	uint16_t Port;
};

}


#endif
